
'use strict';
var app = app || {};

(function () {
	var STORAGE_ID = 'catpci-demo';
	app.storage = {
		get: function () {
			return JSON.parse(localStorage.getItem(STORAGE_ID) || '[]');
		},
		put: function (todos) {
			localStorage.setItem(STORAGE_ID, JSON.stringify(todos));
		}
	};
})();

// Device Model
app.Device = function (data) {
	this.name = m.prop(data.name);
	this.lesions = m.prop(data.lesions || []);
	this.diameter = m.prop(data.diameter || 0);
    this.length = m.prop(data.length || 0);
	this.id = m.prop(data.id);
};

app.NewDevice = function (newId) {
	return new app.Device({
		id: newId,
		name: "",
		lesions: [],
		diameter: 0,
		length: 0
	});
}

app.DevName = function (name, id) {
    this.id = m.prop(id);
    this.name = m.prop(name)
}

var approvedDevices = [
	"1: Blinded - Device type unknown",
	"2: Place Holder - Device not in list",
	"3: Atherectomy - Peripheral (any mfr)",
	"4: Balloon - Peripheral (any mfr)",
	"5: Balloon from deployed stent",
	"6: Embolic Protection - Peripheral (any mfr)",
	"7: Extraction Catheter - Peripheral (any mfr)",
	"8: Laser",
	"9: Stent - Peripheral (any mfr)",
	"10: Thrombectomy Catheter - Peripheral (any mfr)",
	"11: ASAHI - Tornus",
	"12: CROSSSAIL Coronary Dilatation Catheter",
	"13: FLEXI-CUT Atherectomy",
	"14: HIGHSAIL Coronary Dilatation Catheter",
	"15: Jostent Coronary Stent Graft",
	"16: Jostent GraftMaster OTW",
	"17: Merlin PTCA Catheter (OTW)",
	"18: Multi-Link Mini Vision OTW Stent",
	"19: Multi-Link Mini Vision RX Stent",
	"20: Multi-Link Pixel Stent OTW",
	"21: Multi-Link Pixel Stent RX",
	"22: Multi-Link Ultra Stent - OTW",
	"23: Multi-Link Ultra Stent - RX",
	"24: Multi-Link Vision OTW Stent",
	"25: Multi-Link Vision RX Stent",
	"26: NC Merlin PTCA Catheter (OTW)",
	"27: OPENSAIL Coronary Dilatation Catheter",
	"28: POWERSAIL Coronary Dilatation Catheter",
	"29: Voyager OTW Balloon",
	"30: Voyager Rx Coronary Dilation Catheter",
	"31: Metricath Gemini Catheter",
	"32: Angiosculpt Scoring Balloon Catheter",
	"33: Trerotola PTD Rotator Drive Unit",
	"34: BioDivYsio Stents (phosphorylcholine)",
	"35: Transluminal Extraction Catheter (TEC)",
	"36: Rithron-XR Coronary Stent System",
	"37: Tenax-XR Amorphous Silicon Carb. Coated Stent",
	"38: Teneo coronary stent",
	"39: Ace Balloon",
	"40: Andante Balloon",
	"41: BeStent2 w/ Discrete Tech OTW Stent",
	"42: Champion DES (Everlimus)",
	"43: Cutting Balloon Ultra Monorail ",
	"44: Cutting Balloon Ultra OTW ",
	"45: Cutting Balloon Ultra2 (OTW)",
	"46: Cutting Balloon Ultra2 Monorail",
	"47: Express2 OTW stent",
	"48: Express2 RE stent",
	"49: FilterWire EX Emoblic Protection System",
	"50: FilterWire EZ Embolic Protection System",
	"51: Flextome Cutting Balloon Monorail",
	"52: Flextome Cutting Balloon OTW",
	"53: FX miniRAIL Rx PTCA ",
	"54: Galileo III",
	"55: Graft Ace Balloon ",
	"56: L Ranger OTW Balloon",
	"57: Liberte OTW Stent",
	"58: Liberte RE Stent",
	"59: Long Ace Balloon ",
	"60: Magic WALLSTENT Self Expanding Stent",
	"61: Maverick OTW Balloon ",
	"62: Maverick XL Monorail  RE Balloon",
	"63: Maverick(2) Monorail Balloon RE ",
	"64: Multi-Link OTW ZETA Stent",
	"65: Multi-Link PENTA Stent",
	"66: Multi-Link RX ZETA Stent",
	"67: Multi-Link TETRA Stent",
	"68: NC Monorail Balloon RE ",
	"69: NC Ranger OTW Balloon ",
	"70: NIR Elite Monorail RE Stent",
	"71: NIR Elite OTW Stent",
	"72: Pivot Balloon Catheter",
	"73: Quantum Maverick OTW Balloon ",
	"74: Quantum Maverick RE Balloon",
	"75: Radius Self Expanding Stent",
	"76: Rio Aspiration Catheter",
	"77: Rotablator rotational atherectomy system",
	"78: RX ESPRIT Coronary Dilation Balloon",
	"79: SLK-View",
	"80: Surpass Superfusion Perfusion Catheter",
	"81: Symbiot Covered Stent (ePTFE polymer)",
	"82: Taxus Express 2 Monorail Drug Eluting Stent",
	"83: Taxus Express 2 OTW Drug Eluting Stent",
	"84: Taxus Liberte Paclitaxel-Eluting Stent ",
	"85: Accent Balloon ",
	"86: DuraStar RX Balloon Catheter",
	"87: FireStar RX Balloon Catheter",
	"88: SpiderFX Embolic Protection",
	"89: SpideRx Embolic Protection",
	"90: X-Sizer",
	"91: Rinspirator System",
	"92: Silver Hawk Plaque Excision System",
	"93: Diver CE",
	"94: Tacrolimus Eluting Stent",
	"95: Bx SONIC OTW Stent",
	"96: Bx SONIC OTW Stent with HEPACOAT",
	"97: Bx Velocity OTW Stent",
	"98: Bx Velocity OTW Stent with HEPACOAT ",
	"99: Bx Velocity Rx Stent",
	"100: Bx Velocity RX Stent with HEPACOAT ",
	"101: Checkmate",
	"102: CROSSFLEX LC Stent (OTW)",
	"103: Cypher Sirolimus-eluting Stent (OTW)",
	"104: Cypher Sirolimus-eluting Stent (Rx)",
	"105: Frontrunner CTO Catheter",
	"106: NC RAPTOR OTW PTCA ",
	"107: Ninja FX OTW PTCA ",
	"108: RAPTOR OTW PTCA ",
	"109: RAPTORRAIL RE PTCA ",
	"110: TITAN MEGA PTCA ",
	"111: Intraluminal Safe-cross Catheter",
	"112: QuickCat Extraction Catheter",
	"113: TriActiv",
	"114: Xtract Catheter",
	"115: Metricath GPS Catheter",
	"116: Driver MX2 (RX)",
	"117: Driver OTW Coronary Stent",
	"118: Driver Zipper MX Coronary Stent",
	"119: Endeavor Stent (OTW)",
	"120: Endeavor Stent MX2",
	"121: Endeavor Stent RX",
	"122: Export Catheter",
	"123: Export XT Catheter",
	"124: GuardWire Temporary Occlusion",
	"125: Micro Driver (OTW)",
	"126: Micro Driver MX2 (RX)",
	"127: NC Stormer OTW Balloon ",
	"128: NC Stormer Zipper MX",
	"129: Percusurge",
	"130: R Stent Prodigy",
	"131: S660 with Discrete Technology OTW Stent",
	"132: S670 with Discrete Technology OTW Stent",
	"133: S7 with Discrete Technology OTW Stent",
	"134: S7 Zipper MX Multi-Exchange Stent",
	"135: Sprinter Balloon",
	"136: Sprinter MX2 (RX)",
	"137: Sprinter OTW",
	"138: Stormer OTW Balloon ",
	"139: Stormer Zipper MX",
	"140: Beta-Cath",
	"141: R Stent Evolution",
	"142: R Stent SVS (small vessel system)",
	"143: Cardio-Path",
	"144: AngioJet Xpeedior+120 Thrombectomy Catheter",
	"145: AVX Thrombectomy Catheter",
	"146: DVX Thrombectomy Catheter",
	"147: Fetch Aspiration Catheter",
	"148: Spiroflex",
	"149: Spiroflex Ultra",
	"150: Spiroflex VG Thrombectomy Catheter",
	"151: XMI Ultra Thrombectomy Catheter",
	"152: XMI-OTW Thrombectomy Catheter",
	"153: XMI-RX Thrombectomy Catheter",
	"154: XVG Thrombectomy Catheter",
	"155: XVG Ultra Thrombectomy Catheter",
	"156: Viva Balloon",
	"157: Quantum Ranger OTW Balloon ",
	"158: Proxis Embolic Protection System",
	"159: Pronto Extraction Catheter",
	"160: Promus DES RX",
	"161: Promus DES OTW",
	"162: Xience DES RX",
	"163: Xience DES OTW",
	"164: NC Stormer MX2",
	"165: Taxus Express2 ATOM - OTW",
	"166: Taxus Express2 ATOM - RX",
	"167: Voyager NC - OTW",
	"168: Voyager NC - RX",
	"169: LipiScan Coronary Imaging System",
	"170: Taxus Liberte Stent - OTW",
	"171: Taxus Liberte Stent - RX",
	"172: Apex Monorail",
	"173: Apex (OTW)",
	"174: Endeavor Sprint - RX",
	"175: NC Sprinter - RX",
	"176: Sprinter Legend - RX",
	"177: Driver RX",
	"178: Micro Driver RX",
	"179: Export AP Catheter",
	"180: Endeavor Sprint - OTW",
	"181: Apex Monorail - Flex",
	"182: Apex Monorail - Push",
	"183: Apex OTW - Flex",
	"184: Apex OTW - Push",
	"185: Prime Wire",
	"186: Pronto LP",
	"187: Pronto V3",
	"188: Taxus Liberte Atom - OTW",
	"189: Taxus Liberte Atom - RX",
	"190: Xience V DES - OTW - Multilink Vision",
	"191: Xience V DES - RX - Multilink Vision",
	"192: Xience V DES - OTW - Multilink MiniVision",
	"193: Xience V DES - RX - Multilink MiniVision",
	"194: Sprinter Legend - OTW",
	"195: Export AP Catheter",
	"196: VeriFLEX RX",
	"197: VeriFLEX OTW ",
	"198: TAXUS Liberte Long Stent",
	"199: NC Quantum Apex Monorail",
	"200: NC Quantum Apex OTW",
	"201: Integrity OTW Coronary Stent",
	"202: Integrity RX Coronary Stent",
	"203: Mini-Trek Rx",
	"204: Mini-Trek OTW",
	"205: Trek Rx",
	"206: Trek OTW",
	"207: Xpress-Way Rx",
	"208: Pronto V4",
	"209: ION Stent OTW",
	"210: ION Stent Monorail",
	"211: NC Trek OTW",
	"212: NC Trek Rx",
	"213: Xience Nano Rx",
	"214: ASAP",
	"215: Promus Element RX",
	"216: Promus Element OTW",
	"217: Xience Prime LL Rx",
	"218: Resolute Integrity Rx",
	"219: Resolute Integrity OTW",
	"220: Promus Element Plus Rx",
	"221: Promus Element Plus OTW",
	"222: Empira Rx",
	"223: Empira NC Rx",
	"224: Crossboss CTO Catheter",
	"225: Stingray CTO Catheter",
	"226: Emerge PTCA Dilatation Catheter OTW",
	"227: Emerge PTCA Dilatation Catheter Monorail",
	"228: PriorityOne Aspiration Catheter",
	"229: Multi-Link 8 LL Rx",
	"230: Clearway Rx",
	"231: Glider PTCA Balloon Catheter OTW",
	"232: Presillion Plus CoCr Coronary Stent Rx",
	"233: Xience Xpedition DES Rx",
	"234: Xience Xpedition DES OTW",
	"235: Xience Xpedition LL DES OTW",
	"236: Xience Xpedition LL DES Rx",
	"237: Xience Xpedition SV DES OTW",
	"238: Xience Xpedition SV DES Rx",
	"239: Fetch®2 Aspiration Catheter  ",
	"240: BioMatrix Flex",
	"241: Fetch 2 Aspiration Catheter",
	"242: SeQuent Please Balloon",
	"243: Self-Apposing Stent DES",
	"244: Self-Apposing Stent BMS",
	"245: Export Advance Catheter",
	"246: DIAMONDBACK 360 ",
	"247: GRAFTMASTER RX Stent",
	"248: Promus PREMIER OTW",
	"249: Promus PREMIER RX",
	"250: PRO-Kinetic Energy Stent OTW",
	"251: PRO-Kinetic Energy Stent RX",
	"252: AngioSculpt Taper",
	"253: Rebel Stent RX",
	"254: Rebel Stent OTW",
	"255: NC Euphora RX",
	"256: NC Euphora OTW",
	"257: Xience Alpine RX",
	"258: Xience Alpine OTW",
	"259: NC Mozec RX",
	"260: Chocolate Balloon RX",
	"261: Chocolate Balloon OTW",
	"262: NC Emerge RX",
	"263: NC Emerge OTW",
	"264: PRO-Kinetic Energy Stent RX",
	"265: NIRxcell CoCr Stent RX",
	"266: SYNERGY Stent RX",
	"267: SYNERGY Stent OTW",
	"268: Resolute Onyx Stent RX",
	"269: Resolute Onyx Stent OTW",
	"270: Resolute Onyx Stent OTW",
	"271: Threader Micro-Dilatation Balloon RX",
	"272: Threader Mico-Dilatation Balloon OTW",
	"273: Ryujin Plus Balloon OTW ",
	"274: OPN NC Balloon RX  ",
	"275: ELCA  Coronary Laser Atherectomy Catheter RX",
	"276: ELCA Coronary Laser Atherectomy Catheter OTW  ",
	"277: NIC Nano CTO Balloon RX",
	"278: NIC Nano CTO Balloon OTW",
	"279: XPRESS-WAY Extraction Catheter RX",
	"280: Magic Touch Balloon RX",
	"281: Euphora Balloon RX",
	"282: Euphora Balloon OTW",
	"283: Airtimes Balloon RX",
	"284: Apollo NC Balloon RX",
	"285: MegaVac Vaccum Extraction Catheter",
	"286: AngioJet Ultra Coronary ThrombectomySystem",
	"287: DESyne Coronary Stent",
	"288: DESolve Bioresorbable Coronary Scaffold System",
	"289: Sapphire NC  Dilatation Catheter ",
	"290: MGuard Embolic Protection Stent",
	"291: Yukon Choice Coronary Stent",
	"292: Coroflex ISAR Coronary Stent",
	"293: COMBO Dual Therapy Stent",
	"294: RotaLink Plus Rotational Atherectomy System",
	"295: Sapphire II NC Dilatation Catheter",
	"296: Azule Stent",
	"297: Coroflex Blue NEO Stent",
	"298: Firebird2 Stent",
	"299: SatinFlex Stent",
	"300: AXXESS Bifurcated Stent System",
	"301: Tazuna Balloon",
	"302: Hiryu NC Balloon",
	"303: Nobori Stent",
	"304: Thrombuster II Extraction Catheter",
	"305: RotaLink Plus Rotational Atherectomy System",
	"306: Xience Prime SV Stent",
	"307: SYNERGY Bioabsorbable Stent",
	"308: Ultimaster Coronary Stent System",
	"309: JIVE PTCA Balloon Catheter",
	"310: ACROSS CTO ST Balloon",
	"311: FORTIS II Balloon",
	"312: IKAZUCHI X Balloon",
	"956: Brachy Therapy",
	"957: Chronic Total Occlusion",
	"959: Extraction Catheter",
	"961: Thrombectomy",
	"962: Atherectomy",
	"963: Promus PREMIER",
	"964: MINI Trek II",
	"965: Corsair Microcatheter",
	"966: ReFLOW Aspiration Catheter",
	"967: IN.PACT Falcon",
	"968: FLASH Ostial System RX",
	"969: Absorb Bioresorbable Vascular Scaffold System",
	"970: Glider PTCA Balloon Catheter RX"
];


// Device Selections



